
###
GET http://localhost:8000/api/Books

###
GET http://localhost:8000/api/Books/7

###
PUT  http://localhost:8000/api/Books/7
Content-Type: application/json

{ 
    "id": 7,
    "Title": "The River and the source"
  
}

###
POST  http://localhost:8000/api/Books
Content-Type: application/json

{ 
    "id": 8,
    "Title": "The RTiver and the source",
    "Author": "Susan K Matei",
    "Year": "2005"
}
###
DELETE  http://localhost:8000/api/Books/8

